//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddNReadApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int IDCart { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
