//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddNReadApp
{
	using AddNReadApp.Core;
	using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.Windows.Media;

	public partial class Product : ObservaleObject
	{
		private string _image;
        public int ID { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Max_discount { get; set; }
        public string Manufacturer { get; set; }
        public string Provider { get; set; }
        public string Category { get; set; }
        public Nullable<int> Current_discount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
		public string CurectImage
		{
			get
			{
				if (String.IsNullOrEmpty(Image) || String.IsNullOrWhiteSpace(Image))
				{
					return "Images/picture.png";
				}
				else
				{
					return $"Images/{Image}";
				}
			}
		}

		public string Image
		{
			get { return _image; }
			set
			{
				_image = value;
				OnPropertyChanged(nameof(CurectImage));
			}
		}
	}
}
